Models/TripVM.cs
using System;
using IPBLL;
using IPDAL;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TripTaskEFApp.Models
{
    public class TripVM
    {
        public int TripId { get; set; }     
        public string Destination { get; set; }
        public string Description { get; set; }

        public  DateTime? StartDate { get; set; }

        public DateTime? EndDate { get; set; }   
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TripTaskEFApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/TempTripController.cs
using IPBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace TripTaskEFApp.Controllers
{
    public class TempTripController : Controller
    {
        // GET: TempTrip
        public ActionResult Index()
        {
            TripService tripService = new TripService();
           var  trips = tripService.GetTrips();
            return View(trips);
        }
    }
}

Controllers/TripController.cs
using AutoMapper;
using IPBLL;
using IPDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TripTaskEFApp.Models;

namespace TripTaskEFApp.Controllers
{
    public class TripController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
         
        [HttpGet]
        public JsonResult GetTrips()
        {
            TripService tripService = new TripService();
            var trips = tripService.GetTrips();

            List<TripVM> tripVMs = new List<TripVM>();
            
             
            Mapper.Map(trips, tripVMs);

            return Json(tripVMs, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetTripById(int Id)
        {
            TripService tripService = new TripService();
            var trip = tripService.GetTrip(Id);
            return Json(trip, JsonRequestBehavior.AllowGet);
 
        }

        [HttpPost]

        public JsonResult AddTrip(Trip trip)
        {
            TripService tripService = new TripService();
            var tripAdded = tripService.AddTrip(trip);  
             
            return Json(tripAdded , JsonRequestBehavior.AllowGet);
        }


        [HttpPost]

        public JsonResult UpdateTrip(Trip trip)
        { 
            TripService tripService = new TripService();
            var tripUpdated = tripService.UpdateTrip(trip);
            return Json(tripUpdated, JsonRequestBehavior.AllowGet); 
        }
         
        [HttpPost]

        public JsonResult DeleteTrip(int tripId)
        {
            TripService tripService = new TripService();
            if (tripService.DeleteTrip(tripId))
            {
                return Json(JsonRequestBehavior.AllowGet);
            }
            return null;
        }

    }

}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Trips", "Index", "Trip", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/TempTrip/Index.cshtml
@model IEnumerable<IPDAL.Trip>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TripId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TripId }) |
            @Html.ActionLink("Delete", "Delete", new {Id=item.TripId })
        </td>
    </tr>
}

</table>

Views/Trip/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
 <link href="~/Content/bootstrap.css" rel="stylesheet" />
 
<h2>Index</h2>
 
<script type="text/javascript">
    $(document).ready(function () {
        loadData();
    })

    function loadData() {

        $.ajax({

            url: "/Trip/GetTrips",
            type: "GET",
            contentType: "application/json",
            dataType: "json",
            success: function (response) {
                var html = '';
                $.each(response, function (key, item) {
                    html += '<tr>',
                        html += '<td>' + item.Destination + '</td>';
                    html += '<td>' + item.Description + '</td>';
                    html += '<td>' + new Date(parseInt(item.StartDate.substr(6))).toLocaleDateString() + '</td>';
                    html += '<td>' + new Date(parseInt(item.EndDate.substr(6))).toLocaleDateString() + '</td>';
                    html += '<td> <a href = "#" onclick="return getTripById(' + item.TripId + ')"> Edit Trip </a> | <a href = "#" onClick=Delete(' + item.TripId + ')>Delete Trip</a></td>';
                    html += '</tr>'
                });
                $('.tbody').html(html);
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }

        })
    }

    function Add() {
        var tripObj = {
            Destination: $('#destination').val(),
            Description: $('#description').val(),
            StartDate: $('#startdate').val(),
             EndDate: $('#enddate').val()

        }

        $.ajax({
            url: "/Trip/AddTrip",
             
            type: "POST",
            data: JSON.stringify(tripObj),

            contentType: "application/json",
            dateType: "json",
            success: function (response) {
                console.log(response);
                if (response == true) {
                    loadData();
                    $('#myModal').modal('hide');
                    $('.modal-backdrop').remove();
                }
                else {
                    $('#errorMessage').text(' trip start date must be less than trip end date ');
                }
                
               
            },
            error: function (errormessage) {
                alert(errormessage.responseText);

            }
        })
    }

    function getTripById(tripId) {
 
        $.ajax({
            url:"/Trip/GetTripById/" + tripId ,
            type: "GET" ,
            contentType: "application/json" ,
            dataType: "json" ,
            success: function (response) {
                $('#tripid').val(response.TripId);
                $('#destination').val(response.Destination);
                $('#description').val(response.Destination);

                var startDate = new Date(parseInt(response.StartDate.substr(6))).toISOString().split('T')[0];
                var endDate = new Date(parseInt(response.EndDate.substr(6))).toISOString().split('T')[0];
                $('#startdate').val(startDate);
                $('#enddate').val(endDate);

                $('#myModal').modal('show');
                $('#btnUpdate').show();
                $('#btnAdd').hide();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            } ,
        })
    }

    function update() {
        var tripObj = {
            TripId: $('#tripid').val(),
            Destination: $('#destination').val(),
            Description: $('#description').val(),
            StartDate: $('#startdate').val(),
            EndDate: $('#enddate').val()

        }
        $.ajax({
            url: "/Trip/UpdateTrip",
            data: JSON.stringify(tripObj),
            type:"POST",
            contentType: "application/json",
            dateType: "json",
            success: function (response) {
                loadData();
                $('#myModal').modal('hide');
                $('.modal-backdrop').remove();

            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        })
    }

    function Delete(tripId) {
        var ans = confirm('are u sure u want to delete trip?');
        if (ans) {
            $.ajax({
                url: "/Trip/DeleteTrip/",
                data: JSON.stringify({ tripId: tripId }),
                type: "POST",
                contentType: "application/json",
                dateType: "json",
                success: function (response) {
                    loadData();

                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }

            })
        }
    } 

    function clearTextBoxes() {
        $('#destination').val("");
        $('#description').val("");
        $('#startdate').val("");
        $('#enddate').val("");
        $('#btnUpdate').hide();
        $('#btnAdd').show();
    }

</script>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal" onclick="clearTextBoxes();">Add new trip</button>
 
<center> <h2> My upcoming Trips</h2></center>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Destination</td>
            <td>Description</td>
            <td>Trip Start Date</td>
            <td>Trip End Date</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody class="tbody">
    </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class=" modal-header">
                <h4 class="modal-title">Add Trip</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="tripid" />

                <form>
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="destination" placeholder="destination of trip" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="description" placeholder="destination of trip" />
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="date" class="form-control" id="startdate" />
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="date" class="form-control" id="enddate" />
                            </div>
                        </div>
                    </div>
                    <p style="color:red" id="errorMessage"></p>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" id="btnAdd" onclick="return Add();">Add</button>
                <button type="button" class="btn btn-outline-primary" id="btnUpdate" onclick="update();">Update</button>
            </div>
        </div>
    </div>
</div>